version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: edugame_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edugame_db
    networks:
      - edugame-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-backend:
    build:
      context: ./backend-spring
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/edugame_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edugame-network

  flask-backend:
    build:
      context: ./backend-flask
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend-flask:/app
    depends_on:
      - spring-backend
    networks:
      - edugame-network

  nextjs-frontend:
    build:
      context: ./frontend-next
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  edugame-network:
    driver: bridge
